### ISSUE TITLE
`worker.js:2737 [mp4 @ 0x3a61d80] Unsupported pixel format (-1)`

### ISSUE THREAD

**Issue by lucadalli** [Banou26/libav-wasm#7]
Facing error `worker.js:2737 [mp4 @ 0x3a61d80] Unsupported pixel format (-1)` when trying to apply the basic usage example shown in the readme.

Are VP9-encoded WebM files supported?

**Comment by Banou26** [comment]
Right now the only format supported is `mkv(matroska)` as input, and `mp4` as output.
I'm just not really sure why would you want to remux `webm` into `mp4`, the main use case for this library is to playback non playable formats in your browser, and `webm` is widely supported across browsers.
If you really need it i can try adding support for it this weekend though.
